accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignupPage

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupPage.as_view(), name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from webchat.urls import websocket
from webchat import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('ws/<str:room>', views.websocket_server),
    path('webchat/', include('webchat.urls', namespace='webchat')),
]

webchat/urls.py
from django.urls import path
from .views import WebChatTop, ChatRoom, CreateChannel


websocket = path
app_name = 'webchat'
urlpatterns = [
    path('top/', WebChatTop.as_view(), name='top'),
    path('create_channel/', CreateChannel.as_view(), name='create_channel'),
    path('chat_room/<str:room_id>/', ChatRoom.as_view(), name='chat_room'),
]

accounts/models.py
from django.db import models

# Create your models here.

webchat/models.py
from django.db import models
from django.contrib.auth.models import User


class Channel(models.Model):
    name = models.CharField(max_length=100, unique=True)
    topic = models.TextField(max_length=255)
    is_private = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    channel = models.ForeignKey(
        Channel, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return ("id:{}, cnannel:{}, user:{}".format(self.id, self.channel, self.user))

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm


class SignupPage(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

webchat/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from asgiref.sync import sync_to_async

from .models import Channel, Message


class WebChatTop(generic.ListView):
    model = Channel
    template_name = 'webchat/top.html'


class CreateChannel(generic.CreateView):
    template_name = 'webchat/create_channel.html'
    model = Channel
    fields = ('name', 'topic', 'is_private')
    success_url = reverse_lazy('webchat:top')


class ChatRoom(LoginRequiredMixin, generic.TemplateView):
    template_name = 'webchat/chat_room.html'

    # オーバーライドしてurl path chat_room/<str:room> を取得
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room_id = self.kwargs.get('room_id')
        room_name = Channel.objects.get(id=room_id)
        channel_list = Channel.objects.all()
        message_all = Message.objects.select_related('channel').values(
            'channel__name', 'channel_id', 'user__username', 'user__id', 'message', 'created_at', 'channel__topic').filter(channel_id=room_id)
        context = {
            'room_id': room_id,
            'room_name': room_name,
            'message_all': message_all,
            'channel_list': channel_list
        }
        return context


@sync_to_async
def message_save(channel_id, user_id, message):
    """
    read https://docs.djangoproject.com/en/3.1/topics/async/
    非同期でdbへmessageを書き込む
    """
    print(channel_id, user_id, message)
    save_message = Message(channel_id=channel_id,
                           user_id=user_id, message=message)
    save_message.save()


clients = {}


async def websocket_server(socket, room):
    room_path = "/ws/" + room
    await socket.accept()
    key = socket.headers['sec-websocket-key']
    clients[key] = socket
    try:
        while True:
            data = await socket.receive()
            data_list = data['text'].split(',')
            username, user_id, message = data_list[0], data_list[1], data_list[2]
            await message_save(channel_id=room, user_id=user_id, message=message)
            for i, client in enumerate(clients.values()):
                if client.path == room_path:
                    await client.send_text("{} {}".format(username, message))
    except:
        await socket.close()
        del clients[key]

templates/webchat/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>WebChat Sample</title>
    </head>
    <style>
        html,
        body {
            height: 100%;
        }
    </style>
    <body>
        <div class="header"></div>
        {% block Content %}
        <div class="content"></div>
        {% endblock Content %}
    </body>
</html>

templates/webchat/chat_room.html
{% extends 'webchat/base.html' %} {% block Content %}
<style>
    html,
    body,
    .grid-container {
        height: 100%;
        margin: 0;
    }
    .grid-container {
        display: grid;
        grid-template-columns: 20% 80%;
        grid-template-rows: 8% 84% 8%;
        gap: 0% 0%;
        grid-template-areas:
          "user_detail channel_top"
          "channel_list channel_message"
          "channel_option channel_send";
      }

      .channel_top {
          grid-area: channel_top;
          background-color: FFFFFF;
        }

      .channel_message {
          grid-area: channel_message;
          background-color: FFFFFF;
          overflow-y: scroll;
        }
      .messageArea > ul {
          padding:0;
      }
      .message_box {
          padding: 2px;
      }
      .message_box:hover {
        background-color:#e6e6e6
    }
      .message_user {
          font-weight: bold;
          font-size: small;
      }

      .channel_send { grid-area: channel_send; background-color:FFFFFF }

      .channel_send_form {
          padding: 1px;
          margin: 10px;
      }

      .channel_send_form_text {
          width: 90%;
          height: 30px;
      }
      .channel_send_form_button {
        width: 8%;
        height: 35px;
      }

      .user_detail { grid-area: user_detail;background-color: #1A1D21;color: #FFFFFF }
      .user_detail:hover {
        background-color:#000000
      }

      .user_detail > .username {
        margin-left: 20px;
        margin-top: 20px;
      }

      .channel_list {
          grid-area: channel_list;
          background-color:#1A1D21;
          color: #FFFFFF;
        }



        .channel_list > ul {
            list-style: none;
            padding: 0;
        }
        .channel_list_box:hover {
            background-color:#000000;
        }
        .channel_list_box > li {
            margin-left: 20px;
            padding: 1px;
        }
        .channel_list_box > li > a {
            text-decoration: none;
        }
        .channel_list_box > li > a:link,a:visited,a:hover,a:active {
          color: #FFFFFF;

        }

        .channel_option { grid-area: channel_option;background-color: #1A1D21;color: #FFFFFF }

        .channel_option > .channel_option_link {
            margin-left: 20px;
            margin-top: 20px;
          }

</style>
<div class="grid-container">
    <div class="user_detail">
        <div class="username">
            {{ user.username }}
        </div>
    </div>
    <div class="channel_list">
        <ul>
            {% for channel in channel_list %}
            <div class="channel_list_box">
                    <li><a href="{% url 'webchat:chat_room' channel.id %}"># {{ channel }}</a></li>
            </div>
            {% endfor %}
        </ul>
    </div>
    <div class="channel_option">
        <div class="channel_option_link">
           <a href="{% url 'webchat:create_channel' %}">create channel</a>
        </div>
    </div>
    <div class="channel_top">
        <div class="channel_name"># {{ room_name }} </div>
        <div id="status"></div>
    </div>
    <div class="channel_message">
        <div class="messageArea">
            <ul id="messageList">
                {% for message in message_all %}
                <div class="message_box">
                    <li>
                        <div class="message_user">
                            {{ message.user__username }} {{ message.created_at }}
                        </div>
                        <div class="message_text">
                            {{ message.message }}
                        </div>
                    </li>
                </div>
                {% endfor %}
            </ul>
        </div>

    </div>
        <div class="channel_send">
            <div class="channel_send_form">
                <input
                    id="textMessage"
                    type="text"
                    class="channel_send_form_text"
                    placeholder="{{ room_name }} room へmessageを送信"
                />
                <button
                    class="channel_send_form_button"
                    type="button"
                    id="sendMessage"
                >
                    Send
                </button>
            </div>
        </div>
    </div>

    </div>

    <script>
        let webSocket = new WebSocket("ws://127.0.0.1:8000/ws/{{ room_id }}");
        let text_message = document.querySelector("#textMessage");
        let send_button = document.querySelector("#sendMessage");
        let message_area = document.querySelector("#messageList");
        let channel_message = document.querySelector(".channel_message");
        let status = document.querySelector("#status");

        channel_message.scroll(0, channel_message.scrollHeight);

        webSocket.onopen = () => {
            status.innerText = "Server connect...";
        };
        webSocket.onmessage = (message) => {
            let newLi = document.createElement("li");
            newLi.classList.add("list-group-item");
            newLi.innerText = message.data;
            message_area.appendChild(newLi);
            channel_message.scroll(0, channel_message.scrollHeight);
        };

        send_button.addEventListener("click", () => {
            send_message =
                "{{ user.username }}\, {{ user.id }}\," + text_message.value;
            sendMessage(send_message);
        });

        function sendMessage(message) {
            webSocket.send(message);
            text_message.value = "";
        }
    </script>

    {% endblock Content %}
</div>

templates/webchat/create_channel.html
<h1>Create Page</h1>

<form action="" method="POST">
    {% csrf_token %} {{ form.as_p}}
    <input type="submit" value="作成する" />
</form>

templates/webchat/top.html
{% if user.is_authenticated %}
    {{ user.username }}
{% else %}
    <a href="{% url 'login' %}">Login</a></li>
{% endif %}


<h1>Top Page</h1>
<ul>
    {% for item in object_list %}
        <li>{{ item.id }}: <a href="{% url 'webchat:chat_room' item.id %}">{{ item.name }}</a>: {{ item.topic }}: {{ item.is_private }}: {{ item.created_at }}</li>
    {% endfor %}
</ul>
<a href="{% url 'webchat:create_channel' %}">create channel</a>